sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lgdevlop/travis-playground -f Dockerfile.dev .

script:
  - docker run -e CI=true lgdevlop/travis-playground npm run test